### ISSUE TITLE
[AI] Get metrics that measuring consumer video and guide video from databases.

### ISSUE THREAD

**Issue by insung3511** [ReHab-Web/ReHab-ML#3]
### Description
Consumer 에게 적용될 기능 구현에 대한 스프린트 Issue 입니다. 기존에 Database에 등록된 영상(Guide Video)과 Json을 갖고 비교를 하여 metrics를 구하는 것을 목표로 두고 있으며 Guide Video에서 미리 추출된 Json 파일을 갖고와서 Consumer Video와 비교를 거칠 예정입니다.

### In Progress
- [x] #8
- [x] 추출된 Json Skeleton 파일과 Consumer Video에서 추출한 Json Skeleton 의 Metrics 구하기

**Comment by insung3511** [comment]
@PortalCube @osohyun0224 Frontend 팀한테 여쭤보고 싶은 내용이 있습니다.

우선 Video Register 부분은 마무리 되어서 이전에 공유 드렸던 Postman Document와 동일합니다. 다만 Metrics Consumer 는 어떻게 처리를 해야할지 고민입니다. 고민 중인 부분은 아래와 동일합니다.

- Program ID는 int인가? 아니면 str인가?
- Metrics를 구하는 과정에서 Guide Video와 Consumer Video의 영상 길이가 달라지면 Metrics 연산 불가하다. 만약에 Gudie Video의 영상 길이가 00:15:00 일때, Consumer Video가 00:15:14 로 보내준다면 어떤 기준으로 잘라야 하는가? 혹은 Frontend layer에서 이를 맞추어서 보내줄 것인가?
 
우선 이 정도 있을거 같습니다. 확인 하시고 답변 부탁드리겠습니다.

**Comment by PortalCube** [comment]
> Program ID는 int인가? 아니면 str인가?

백엔드에서 Program ID를 int로 저장하는 것 같기에 int로 보내드릴 것 같습니다!

> Metrics를 구하는 과정에서 Guide Video와 Consumer Video의 영상 길이가 달라지면 Metrics 연산 불가하다. 만약에 Gudie Video의 영상 길이가 00:15:00 일때, Consumer Video가 00:15:14 로 보내준다면 어떤 기준으로 잘라야 하는가? 혹은 Frontend layer에서 이를 맞추어서 보내줄 것인가?

저희가 MediaRecorder로 최대한 15초를 맞춰서 보내드릴 생각이지만, 브라우저가 송신한 데이터가 15초보다 길거나 짧으면 맨 앞에서 15초를 자르면 될 것 같습니다.

즉, 15초를 초과한 프레임은 삭제하는 방식이면 될 것 같습니다!

**Comment by insung3511** [comment]
사실 두번째 내용은 저희가 직접 시연을 하면서 수정하는 부분이 생길거 같네요... 우선 경재님이 말씀해주신 내용 처럼 초과하면 자르도록 하겠습니다. 아마 제 생각에는 _"Client 단에서 언제까지 녹화를 하는가?"_ 도 얘기가 되어야할거 같아요. 우선적으로는 Guide 영상보다 초과되면 자르도록 하겠습니다.

```
Case #1:
Client에서 영상을 일단 녹화. 이후에 AI Server로 전송 하게 되면 AI Server에서는 전처리 과정을 거치면서 Guide Video와 영상 길이가 동일하게 함.

Case #2:
Client에서 영상을 Guide Video와 동일한 시간대로 녹화하고 AI Server에 전송.

Case #3 (Maybe...?):
중단을 하더라도 그냥 보내준 길이 만큼 AI Server에서 자르면 그 만큼 비교하여 Metrics 반환.
```
